### ISSUE TITLE
upkeep: can we archive/ deprecate this repo? 

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.plot.internal#10]
@MonikaFu do you know if this is actively used anywhere? Are you actively developing it?

**Comment by MonikaFu** [comment]
I'm not actively developing it but not sure if we should deprecate it. The time it can be used is when generating meta results which is not often but I expect that it might be used for the upcoming COP.

**Comment by jdhoffa** [comment]
Ok, happy to keep it then to air on the side of caution! 😊 

Closing this issue without action.
